DROP DATABASE IF EXISTS `test`;

CREATE DATABASE `test`
            DEFAULT COLLATE 'utf8mb4_unicode_ci';
			
USE `test`;
CREATE TABLE `part` (
  `PART_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PART_NAME` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `PART_REQUIRED` tinyint(4) NOT NULL,
  `PART_QUANTITY` int(11) NOT NULL,
  PRIMARY KEY (`PART_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('CPU',1,10);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('RAM',1,10);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('Mother Board',1,10);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('PSU',1,10);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('HDD SATA',1,10);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('Computer Case',1,10);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('Mouse',0,10);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('Key Board',0,23);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('Sound Card',0,11);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('WiFi Adapter',0,5);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('SSD',0,9);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('USB Hub',0,4);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('LCD Monitor',0,10);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('Web Camera',0,17);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('Microphone',0,11);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('Headphones',0,13);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('Network Adapter',0,12);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('USB Bluetooth Adapter',0,11);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('Computer Speakers',0,20);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('USB Led Lamp',0,25);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('Mobile hard disk',0,15);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('HDD Fan',0,20);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('USB Fan Gadget',0,20);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('PCIE Adapter M.2',0,3);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('DVD Optical Drive',0,10);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('Power Bank',0,8);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('External Optical Drive DVD/CD',0,4);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('Gamepad',0,3);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('Cardreader',0,1);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('Network Filter',0,10);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('Video Card',0,10);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('Video PC Capture',0,2);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('RAM Radiator',0,7);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('Thermal Grease CPU',0,100);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('USB Flash Memory',0,50);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('Micro SD',0,50);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('CPU cooler',0,30);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('SATA IDE Adapter',0,50);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('HDD SAS',0,10);
INSERT INTO `test`.`part` (`PART_NAME`,`PART_REQUIRED`,`PART_QUANTITY`)VALUES ('HDD IDE',0,5);
